### ISSUE TITLE
Compile failure w/ base-4.7

### ISSUE THREAD

**Issue by hvr** [gmalecha/skip-list#1]
Welcome to Hackage!

I've noticed a compile failure with `base-4.7` (i.e. GHC 7.8):

```
Configuring library for skip-list-0.1.0.0..
Preprocessing library for skip-list-0.1.0.0..
Building library for skip-list-0.1.0.0..
[1 of 1] Compiling Data.SkipList    ( src/Data/SkipList.hs, /tmp/matrix-worker/1500756479/dist-newstyle/build/x86_64-linux/ghc-7.8.4/skip-list-0.1.0.0/build/Data/SkipList.o )

src/Data/SkipList.hs:37:10:
    Not in scope: type constructor or class ‘Foldable’
```

I've already fixed the meta-data for your package (see
https://hackage.haskell.org/package/skip-list-0.1.0.0/revisions/) to specify more accurately which version range of `base` the `skip-list` package is compatible with; so there's no immediate action needed. Depending on whether you want to support `base-4.7`, please either include the tighter `base >= 4.8` lower bound in the next rlease of `skip-list` (or alternatively make `skip-list` compatible with `base-4.7`).

If you have any questions, please feel free to ask me!

**Comment by gmalecha** [comment]
Thanks. I've fixed it.
